apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
  namespace: signadot
spec:
  endpoints:
    - path: /metrics/signadot
      port: 8080
      scheme: http
  selector:
    matchLabels:
      control-plane: controller-manager
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent-metrics
  namespace: signadot
spec:
  endpoints:
    - path: /metrics
      port: 9090
      scheme: http
  selector:
    matchLabels:
      app: signadot-agent

