apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: rabbitmq-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      annotations:
        sidecar.signadot.com/inject: "true"
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: ghcr.io/emminex23/rabbitmq-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"

        # Queue configuration (baseline)
        - name: QUEUE_NAME
          value: "consumer-baseline"
        - name: QUEUE_DURABLE
          value: "true"
        - name: QUEUE_AUTO_DELETE
          value: "false"

        # RouteServer config (baseline workload identifiers)
        - name: ROUTESERVER_URL
          value: "http://routeserver.signadot.svc:7778"
        - name: BASELINE_KIND
          value: "Deployment"
        - name: BASELINE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BASELINE_NAME
          value: "consumer"
